# Generated by Django 3.1.5 on 2021-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0003_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='order_hash',
            field=models.SlugField(default='None', max_length=100),
        ),
    ]
