# Generated by Django 3.1.5 on 2021-02-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0004_auto_20210208_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='order_hash',
            new_name='slug',
        ),
    ]
