# Generated by Django 3.1.5 on 2021-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0005_auto_20210208_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='goods',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='slug',
            field=models.SlugField(default='None', max_length=255),
        ),
    ]
