# Generated by Django 3.1.5 on 2021-01-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No name', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
