# Generated by Django 3.1.5 on 2021-01-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noname cat', max_length=250)),
                ('id_rozetka', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Noname', max_length=300)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('id_rozetka', models.IntegerField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True)),
                ('images', models.CharField(blank=True, max_length=700)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(blank=True)),
                ('is_active', models.BooleanField(max_length=100)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ManyToManyField(to='my_shop.Categories')),
            ],
            options={
                'ordering': ['-date_add'],
            },
        ),
    ]
