# Generated by Django 3.1.5 on 2021-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_rozetka',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
