# Generated by Django 3.1.5 on 2021-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_auto_20210129_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
