# Generated by Django 3.1.5 on 2021-01-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_auto_20210123_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(default=1)),
                ('title', models.CharField(default='Empty', max_length=200)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('ssid', models.CharField(default='empty', max_length=150)),
            ],
        ),
    ]
