# Generated by Django 3.1.5 on 2021-01-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0003_auto_20210129_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='Noname cat', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
