# Generated by Django 3.1.5 on 2021-01-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0004_auto_20210129_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
