# Generated by Django 3.1.5 on 2021-02-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OlxProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_olx', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('entry_date', models.CharField(default='', max_length=150, null=True)),
                ('author_link', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
    ]
