# Generated by Django 3.1.5 on 2021-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_olxproduct_link_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxproduct',
            name='price',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
