# Generated by Django 3.1.5 on 2021-02-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0003_auto_20210221_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
    ]
