# Generated by Django 3.1.5 on 2021-01-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(default='Noname cat', max_length=250)),
                ('cat_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(default='Noname', max_length=300)),
                ('id_entry', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('link', models.CharField(max_length=200)),
                ('images', models.CharField(blank=True, max_length=700)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('cid', models.ManyToManyField(to='rozetka.Categories')),
            ],
        ),
    ]
