# Generated by Django 3.1.5 on 2021-01-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozetka', '0002_auto_20210126_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='full_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='categories',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
